name: animated_slide_switcher
description: "A Flutter package that provides customizable animated slide switching and additional animation utilities."
version: 0.0.1
repository: https://github.com/marj-international/animated_slide_switcher/tree/main
# homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

topics:
  - animations
  - slide-fade-transitions
  - value-based-animation
  - sliding-animation
  - spring-curve
